/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as DashboardHomeRouteImport } from './routes/dashboard/home'
import { Route as HomeUserRouteImport } from './routes/_home/user'
import { Route as HomeTodoRouteImport } from './routes/_home/todo'
import { Route as HomeTrainingIndexRouteImport } from './routes/_home/training/index'
import { Route as DashboardSystemUserRouteImport } from './routes/dashboard/system/user'
import { Route as DashboardSystemCompanyRouteImport } from './routes/dashboard/system/company'
import { Route as DashboardCoreCompanyStructureRouteImport } from './routes/dashboard/core/company/structure'
import { Route as DashboardCoreCompanyInfoRouteImport } from './routes/dashboard/core/company/info'
import { Route as DashboardCoreCompanyAssetsRouteImport } from './routes/dashboard/core/company/assets'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRoute,
} as any)
const HomeUserRoute = HomeUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => HomeRoute,
} as any)
const HomeTodoRoute = HomeTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => HomeRoute,
} as any)
const HomeTrainingIndexRoute = HomeTrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => HomeRoute,
} as any)
const DashboardSystemUserRoute = DashboardSystemUserRouteImport.update({
  id: '/system/user',
  path: '/system/user',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSystemCompanyRoute = DashboardSystemCompanyRouteImport.update({
  id: '/system/company',
  path: '/system/company',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoreCompanyStructureRoute =
  DashboardCoreCompanyStructureRouteImport.update({
    id: '/core/company/structure',
    path: '/core/company/structure',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCoreCompanyInfoRoute =
  DashboardCoreCompanyInfoRouteImport.update({
    id: '/core/company/info',
    path: '/core/company/info',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCoreCompanyAssetsRoute =
  DashboardCoreCompanyAssetsRouteImport.update({
    id: '/core/company/assets',
    path: '/core/company/assets',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/todo': typeof HomeTodoRoute
  '/user': typeof HomeUserRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/': typeof HomeIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/system/company': typeof DashboardSystemCompanyRoute
  '/dashboard/system/user': typeof DashboardSystemUserRoute
  '/training': typeof HomeTrainingIndexRoute
  '/dashboard/core/company/assets': typeof DashboardCoreCompanyAssetsRoute
  '/dashboard/core/company/info': typeof DashboardCoreCompanyInfoRoute
  '/dashboard/core/company/structure': typeof DashboardCoreCompanyStructureRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/todo': typeof HomeTodoRoute
  '/user': typeof HomeUserRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/': typeof HomeIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/system/company': typeof DashboardSystemCompanyRoute
  '/dashboard/system/user': typeof DashboardSystemUserRoute
  '/training': typeof HomeTrainingIndexRoute
  '/dashboard/core/company/assets': typeof DashboardCoreCompanyAssetsRoute
  '/dashboard/core/company/info': typeof DashboardCoreCompanyInfoRoute
  '/dashboard/core/company/structure': typeof DashboardCoreCompanyStructureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_home': typeof HomeRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_home/todo': typeof HomeTodoRoute
  '/_home/user': typeof HomeUserRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/_home/': typeof HomeIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/system/company': typeof DashboardSystemCompanyRoute
  '/dashboard/system/user': typeof DashboardSystemUserRoute
  '/_home/training/': typeof HomeTrainingIndexRoute
  '/dashboard/core/company/assets': typeof DashboardCoreCompanyAssetsRoute
  '/dashboard/core/company/info': typeof DashboardCoreCompanyInfoRoute
  '/dashboard/core/company/structure': typeof DashboardCoreCompanyStructureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/login'
    | '/register'
    | '/todo'
    | '/user'
    | '/dashboard/home'
    | '/'
    | '/dashboard/'
    | '/dashboard/system/company'
    | '/dashboard/system/user'
    | '/training'
    | '/dashboard/core/company/assets'
    | '/dashboard/core/company/info'
    | '/dashboard/core/company/structure'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/todo'
    | '/user'
    | '/dashboard/home'
    | '/'
    | '/dashboard'
    | '/dashboard/system/company'
    | '/dashboard/system/user'
    | '/training'
    | '/dashboard/core/company/assets'
    | '/dashboard/core/company/info'
    | '/dashboard/core/company/structure'
  id:
    | '__root__'
    | '/_home'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/_home/todo'
    | '/_home/user'
    | '/dashboard/home'
    | '/_home/'
    | '/dashboard/'
    | '/dashboard/system/company'
    | '/dashboard/system/user'
    | '/_home/training/'
    | '/dashboard/core/company/assets'
    | '/dashboard/core/company/info'
    | '/dashboard/core/company/structure'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/dashboard/home': {
      id: '/dashboard/home'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_home/user': {
      id: '/_home/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof HomeUserRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/todo': {
      id: '/_home/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof HomeTodoRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/training/': {
      id: '/_home/training/'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof HomeTrainingIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/dashboard/system/user': {
      id: '/dashboard/system/user'
      path: '/system/user'
      fullPath: '/dashboard/system/user'
      preLoaderRoute: typeof DashboardSystemUserRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/system/company': {
      id: '/dashboard/system/company'
      path: '/system/company'
      fullPath: '/dashboard/system/company'
      preLoaderRoute: typeof DashboardSystemCompanyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/core/company/structure': {
      id: '/dashboard/core/company/structure'
      path: '/core/company/structure'
      fullPath: '/dashboard/core/company/structure'
      preLoaderRoute: typeof DashboardCoreCompanyStructureRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/core/company/info': {
      id: '/dashboard/core/company/info'
      path: '/core/company/info'
      fullPath: '/dashboard/core/company/info'
      preLoaderRoute: typeof DashboardCoreCompanyInfoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/core/company/assets': {
      id: '/dashboard/core/company/assets'
      path: '/core/company/assets'
      fullPath: '/dashboard/core/company/assets'
      preLoaderRoute: typeof DashboardCoreCompanyAssetsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface HomeRouteChildren {
  HomeTodoRoute: typeof HomeTodoRoute
  HomeUserRoute: typeof HomeUserRoute
  HomeIndexRoute: typeof HomeIndexRoute
  HomeTrainingIndexRoute: typeof HomeTrainingIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeTodoRoute: HomeTodoRoute,
  HomeUserRoute: HomeUserRoute,
  HomeIndexRoute: HomeIndexRoute,
  HomeTrainingIndexRoute: HomeTrainingIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

interface DashboardRouteChildren {
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSystemCompanyRoute: typeof DashboardSystemCompanyRoute
  DashboardSystemUserRoute: typeof DashboardSystemUserRoute
  DashboardCoreCompanyAssetsRoute: typeof DashboardCoreCompanyAssetsRoute
  DashboardCoreCompanyInfoRoute: typeof DashboardCoreCompanyInfoRoute
  DashboardCoreCompanyStructureRoute: typeof DashboardCoreCompanyStructureRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSystemCompanyRoute: DashboardSystemCompanyRoute,
  DashboardSystemUserRoute: DashboardSystemUserRoute,
  DashboardCoreCompanyAssetsRoute: DashboardCoreCompanyAssetsRoute,
  DashboardCoreCompanyInfoRoute: DashboardCoreCompanyInfoRoute,
  DashboardCoreCompanyStructureRoute: DashboardCoreCompanyStructureRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
